--[[
	English Locale.
]]

local L = LibStub("AceLocale-3.0"):NewLocale("WhoTaunted", "enUS", true);
if not L then return end

--@localization(locale="enUS", format="lua_additive_table", same-key-is-true=true, handle-unlocalized="english")@
L["'s"] = "'s"
L["<WhoTaunted>"] = "<WhoTaunted>"
L["AOE"] = "AOE"
L["AOE taunted using"] = "AOE taunted using"
L["Announcements"] = "Announcements"
L["Anounce AOE Taunts"] = "Anounce AOE Taunts"
L["Anounce AOE Taunts Output:"] = "Anounce AOE Taunts Output:"
L["Anounce AOE Taunts."] = "Anounce AOE Taunts."
L["Anounce Fails"] = "Anounce Fails"
L["Anounce Fails Output:"] = "Anounce Fails Output:"
L["Anounce Taunts"] = "Anounce Taunts"
L["Anounce Taunts Output:"] = "Anounce Taunts Output:"
L["Anounce taunts that fail."] = "Anounce taunts that fail."
L["Anounce taunts."] = "Anounce taunts."
L["Chat Window"] = "Chat Window"
L["Disable Who Taunted?"] = "Disable Who Taunted?"
L["Disable Who Taunted? in Battlegrounds"] = "Disable Who Taunted? in Battlegrounds"
L["Disables Who Taunted? while you are in a battleground."] = "Disables Who Taunted? while you are in a battleground."
L["Disables Who Taunted?."] = "Disables Who Taunted?."
L["Display Ability"] = "Display Ability"
L["Display the ability that was used to taunt."] = "Display the ability that was used to taunt."
L["Don't show your own failed taunts."] = "Don't show your own failed taunts."
L["Don't show your own taunts."] = "Don't show your own taunts."
L["Failed:"] = "Failed:"
L["General"] = "General"
L["Hide Own Failed Taunts"] = "Hide Own Failed Taunts"
L["Hide Own Taunts"] = "Hide Own Taunts"
L["Immune"] = "Immune"
L["Include Prefix"] = "Include Prefix"
L["Include the"] = "Include the"
L["Party"] = "Party"
L["Raid"] = "Raid"
L["Raid Warning"] = "Raid Warning"
L["Say"] = "Say"
L["Self"] = "Self"
L["Show"] = "Show"
L["Target"] = "Target"
L["The chat window taunts will be announced in when the output is set to"] = "The chat window taunts will be announced in when the output is set to"
L["Where AOE Taunts will be announced."] = "Where AOE Taunts will be announced."
L["Where taunts will be announced."] = "Where taunts will be announced."
L["Where the taunt fails will be announced."] = "Where the taunt fails will be announced."
L["Who Taunted?"] = "Who Taunted?"
L["Yell"] = "Yell"
L["against"] = "against"
L["etc"] = "etc"
L["off of"] = "off of"
L["prefix when a message's output is"] = "prefix when a message's output is"
L["taunt"] = "taunt"
L["taunted"] = "taunted"
L["taunts"] = "taunts"
L["using"] = "using"